+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "1345"
    creation_ts: 2012-02-27 13:21:00 +0100
    short_desc: solid_angle does not work in windows 64bit
    delta_ts: 2012-03-14 10:00:45 +0100
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: forward
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: CLOSED
    resolution: DUPLICATE
    dup_id: "1258"
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P3
    bug_severity: blocker
    target_milestone: '---'
    everconfirmed: "1"
    reporter: ana.hincapie
    assigned_to:
      +content: eelke.spaak
      +@name: Eelke Spaak
    cc: eelke.spaak
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "5361"
        comment_count: "0"
        who:
          +content: ana.hincapie
          +@name: ""
        bug_when: 2012-02-27 13:21:09 +0100
        thetext: |-
          There is a problem running single_angle of the fielfieldtrip-20120125 in a Windows 7 64bit:

          undoing the G1BR balancing
          using headmodel specified in the configuration
          using gradiometers specified in the configuration
          creating dipole grid based on user specified dipole positions
          Invalid MEX-file 'C:\Program Files\fieldtrip-20120125\private\solid_angle.mexw64': The specified module could not be found.

          Error in bounding_mesh (line 71)
              solang = solid_angle(tmp, tri);

          Error in ft_prepare_sourcemodel (line 628)
              tmp = bounding_mesh(grid.pos, pnt, tri);

          Error in ft_prepare_leadfield (line 164)
          grid = ft_prepare_sourcemodel(tmpcfg);

          Error in simulation_beamforming_v4 (line 142)
          [grid]=ft_prepare_leadfield(cfg,data);


          The module is actually in the "....fieldtrip-20120125\private" folder.
      - +@isprivate: "0"
        commentid: "5386"
        comment_count: "1"
        who:
          +content: eelke.spaak
          +@name: Eelke Spaak
        bug_when: 2012-02-29 14:13:25 +0100
        thetext: |-
          Further discussion in bug 1258.

          *** This bug has been marked as a duplicate of bug 1258 ***
      - +@isprivate: "0"
        commentid: "5549"
        comment_count: "2"
        who:
          +content: eelke.spaak
          +@name: Eelke Spaak
        bug_when: 2012-03-14 10:00:45 +0100
        thetext: closing several bugs that have been RESOLVED for a long time
