+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2083"
    creation_ts: 2013-03-29 15:54:00 +0100
    short_desc: 'ft_prepare_atlas: deprecate this function'
    delta_ts: 2013-10-26 18:00:09 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P3
    bug_severity: normal
    target_milestone: '---'
    dependson: "1725"
    blocked: "1114"
    everconfirmed: "1"
    reporter:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    assigned_to:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    cc:
      - johanna.zumer
      - jorn
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "9974"
        comment_count: "0"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-03-29 15:54:14 +0100
        thetext: "This function's functionality should eventually be covered by ft_read_atlas, which supports a much larger amount of different atlases. \nFt_prepare_atlas currently outputs the Afni bricks in old format, not consistent with ft_datatype_segmentation. It contains brick0 and brick1, and the descriptive labels are in the field descr. To move forward I suggest to:\n\n-replace the call to ft_prepare_atlas in ft_sourceplot and ft_volumelookup into a call to ft_read_atlas and update these functions accordingly to deal with the well-defined segmentation format\n-adjust atlas_lookup to also deal with the new segmentation format."
      - +@isprivate: "0"
        commentid: "9975"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-03-29 16:37:23 +0100
        thetext: |-
          as an addition: probably atlas_init and atlas_mask can be removed, they don't seem to be called from anywhere:

          cd ~/matlab/fieldtrip

          grep atlas_init *.m

          grep atlas_mask *.m

          return nothing
      - +@isprivate: "0"
        commentid: "9991"
        comment_count: "2"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-04-02 21:57:09 +0200
        thetext: created a git-branch atlas on my local repo to work with.
      - +@isprivate: "0"
        commentid: "10306"
        comment_count: "3"
        who:
          +content: johanna.zumer
          +@name: Johanna
        bug_when: 2013-04-26 10:54:39 +0200
        thetext: see bug 1725
      - +@isprivate: "0"
        commentid: "10351"
        comment_count: "4"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-05-01 13:46:33 +0200
        thetext: discussed in FT-meeting (also in relation to the ft_sourceparcellate function).
      - +@isprivate: "0"
        commentid: "10595"
        comment_count: "5"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-06-04 15:35:45 +0200
        thetext: |-
          Hi Jörn,
          You might want to keep track of what's happening in this bug.
      - +@isprivate: "0"
        commentid: "10596"
        comment_count: "6"
        who:
          +content: jorn
          +@name: Jörn M. Horschig
        bug_when: 2013-06-04 15:39:21 +0200
        thetext: |-
          ah, thanks, good to know, I missed the meeting on May 1 ;)
          anyway, for now the function works again, so that I can use my beloved atlas again in ft_sourceplot and wonder about my strange beamformed data ^^
      - +@isprivate: "0"
        commentid: "10597"
        comment_count: "7"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-06-04 15:45:49 +0200
        thetext: ow, I thought that ft_sourceplot already used ft_read_atlas. I guess it's time to resolve some conflicts (for me I mean)...
      - +@isprivate: "0"
        commentid: "11415"
        comment_count: "8"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-24 16:52:29 +0200
        thetext: removed atlas_init and atlas_mask in revision 8520
      - +@isprivate: "0"
        commentid: "11419"
        comment_count: "9"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-24 17:00:06 +0200
        thetext: "Deleted ft_prepare_atlas, and \n\nsvn commit -m \"enhancement - added compatibility wrapper in compat directory for now\" ft_prepare_atlas.m"
      - +@isprivate: "0"
        commentid: "11436"
        comment_count: "10"
        who:
          +content: jorn
          +@name: Jörn M. Horschig
        bug_when: 2013-09-25 10:46:29 +0200
        thetext: |-
          (In reply to comment #9)
          you crashed the test script of bug 1114 because of the existence of a compat version. Nothing to worry about, just for the notebook
      - +@isprivate: "0"
        commentid: "11439"
        comment_count: "11"
        who:
          +content: jorn
          +@name: Jörn M. Horschig
        bug_when: 2013-09-25 10:50:45 +0200
        thetext: and test_bug2193 fails, because ft_prepare_atlas is called with cfg.filename but ft_read_atlas without a cfg
      - +@isprivate: "0"
        commentid: "11444"
        comment_count: "12"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-25 11:36:26 +0200
        thetext: |-
          Issue addressed with r8537.

          test_bug1114 still fails, but this is not anymore due to ft_prepare_atlas.
      - +@isprivate: "0"
        commentid: "11445"
        comment_count: "13"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-25 12:01:20 +0200
        thetext: |-
          My bad. It still blocks 1114 (I tested this test_bug1114 with my own FT-version, and not the one on /home/common).

          ft_volumelookup still uses ft_prepare_atlas.

          Hope to work on this today.
      - +@isprivate: "0"
        commentid: "11463"
        comment_count: "14"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-26 09:29:12 +0200
        thetext: 'ft_volumelookup has been updated + test function created as of revision 8546: this should now also fix the crashing test_bug1114 function'
