+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2284"
    creation_ts: 2013-09-13 16:21:00 +0200
    short_desc: 'ft_multiplotTFR: working with connectivity data and cfg.refchannel=''gui'' crashes'
    delta_ts: 2014-01-15 14:46:03 +0100
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P3
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    assigned_to:
      +content: j.schoffelen
      +@name: Jan-Mathijs Schoffelen
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "11301"
        comment_count: "0"
        attachid: "516"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-13 16:21:12 +0200
        thetext: "Created attachment 516\nuse as ft_multiplotTFR(cfg,data) to reproduce\n\nWhen trying to select a reference channel on the 'gui' topography I get an error, which I haven't encountered before.\n\nReference to non-existent field 'dataname'.\n\nError in ft_multiplotTFR>select_multiplotTFR (line 684)\ncfg.dataname = info.dataname;\n\nError in ft_select_channel>select_channel_multiple (line 148)\n      feval(funhandle, label, funargs{:});\n\nError in ft_select_range>evalCallback (line 325)\n    feval(funhandle, funargs{:}, val, cmenulab);\n\nError in ft_select_range (line 159)\n          evalCallback(callback, userData.range);\n \nError while evaluating figure WindowButtonDownFcn\n\nCourse of action: reproduce the error and then fix it."
      - +@isprivate: "0"
        commentid: "11304"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-09-14 18:32:47 +0200
        thetext: 'Note: the bug was first seen on a Mac running matlab2013a.....................'
      - +@isprivate: "0"
        commentid: "12125"
        comment_count: "2"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2013-11-29 12:31:56 +0100
        thetext: |-
          reproduced on a Mac running 2011a. Cause: missing initialization of info.dataname, when cfg.refchannel = 'gui';

          fixed in revision 8914
    attachment:
      +@isobsolete: "0"
      +@ispatch: "0"
      +@isprivate: "0"
      attachid: "516"
      date: 2013-09-13 16:21:00 +0200
      delta_ts: 2013-09-13 16:21:12 +0200
      desc: use as ft_multiplotTFR(cfg,data) to reproduce
      filename: bugdata.mat
      type: application/x-matlab-workspace
      size: "2506203"
      attacher:
        +content: j.schoffelen
        +@name: Jan-Mathijs Schoffelen
      data: REMOVED
