+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "541"
    creation_ts: 2011-03-22 11:39:00 +0100
    short_desc: try-catch construction incompatibe with matlab74
    delta_ts: 2011-03-31 14:13:59 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P1
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    cc: f.depasquale
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "1666"
        comment_count: "0"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-22 11:39:27 +0100
        thetext: |-
          The following was detected to be incompatible with matlab74 on a windows laptop (from Francesco), which I could confirm with the mac version of 74.

          cfg                         = [];
          cfg.dataset                 = 'Subject01.ds';
          cfg.trialdef.eventtype      = 'backpanel trigger';
          cfg.trialdef.eventvalue     = 3; % the value of the stimulus trigger for fully incongruent (FIC).
          cfg.trialdef.prestim        = 1; % in seconds
          cfg.trialdef.poststim       = 2; % in seconds
          cfg = ft_definetrial(cfg);

          this results in the warning/error message on screen


          > In ft_definetrial at 97
          evaluating trialfunction 'trialfun_general'
          ??? Warning: File: /Users/robert/Desktop/course/fieldtrip-20110304/fileio/ft_read_header.m Line: 1020 Column: 15
           This try-catch syntax will continue to work in R2007a,
           but may be illegal or may mean something different in future releases of MATLAB.
           See Release Notes for MATLAB Version 7.4, "Warning Generated by try-catch" for details.

          Error in ==> trialfun_general at 55
          hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat);

          Error in ==> ft_definetrial at 128
              [trl, event] = feval(cfg.trialfun, cfg);
      - +@isprivate: "0"
        commentid: "1667"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-22 11:54:41 +0100
        thetext: |-
          It is a MATLAB version specific bug in MATLAB itself.

          See http://www.mathkb.com/Uwe/Forum.aspx/matlab/131476/Try-catch-error-in-Matlab-version-7-4
          and http://newsgroups.derkeiler.com/Archive/Comp/comp.soft-sys.matlab/2011-01/msg05932.html
      - +@isprivate: "0"
        commentid: "1668"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-22 11:58:13 +0100
        thetext: |-
          the following two code snippets demonstrate the problem

          try
          % do something
          catch me
          % solve the problem
          end

          try
          % do something
          error('something');
          catch
          me = lasterror;
          % solve the problem
          end

          The first one has the problem on matlab74. On a more recent matlab version (7.10, R2010a) both code snippets work exactly the same, so replacing all occuring patterns of version one above by version two should allow matlab74 to be used.
      - +@isprivate: "0"
        commentid: "1669"
        comment_count: "3"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-22 12:24:20 +0100
        thetext: |-
          This problem applies to the following functions

          ./fileio/ft_compile_fileio.m:catch me
          ./fileio/ft_read_header.m:        catch me
          ./forward/ft_compile_forward.m:catch me
          ./ft_compile_mex.m:catch me
          ./ft_componentanalysis.m:    catch ME
          ./ft_prepare_leadfield.m:    catch ME
          ./peer/peercellfun.m:catch nargout_err
          ./peer/peercellfun.m:    catch ME
          ./peer/peerexec.m:  catch nargout_error
          ./peer/private/setcustompwd.m:  catch cd_error
          ./realtime/acquisition/biosemi/acquire.m:catch me
          ./realtime/online_mri/ft_omri_quality.m:  catch me

          I have changed it in all of these functions, the example preprocessing from the tutorial now again runs on matlab74.


          MacBook> svn commit
          Sending        fileio/ft_read_header.m
          Sending        ft_compile_mex.m
          Sending        ft_componentanalysis.m
          Sending        ft_prepare_leadfield.m
          Sending        peer/peercellfun.m
          Sending        peer/peerexec.m
          Sending        peer/private/setcustompwd.m
          Sending        realtime/acquisition/biosemi/acquire.m
          Sending        realtime/online_mri/ft_omri_quality.m
          Transmitting file data .........
          Committed revision 3184.
      - +@isprivate: "0"
        commentid: "1740"
        comment_count: "4"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-03-31 14:13:59 +0200
        thetext: changed the status of most recently resolved/fixed bugs into "CLOSED"
