+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "68"
    creation_ts: 2010-04-16 16:56:00 +0200
    short_desc: double presence in svn, both file and external
    delta_ts: 2011-01-26 15:38:40 +0100
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: WORKSFORME
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    assigned_to:
      +content: fieldtrip-bugs
      +@name: Joint development user
    cc: s.klanke
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "119"
        comment_count: "0"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2010-04-16 16:56:49 +0200
        thetext: |-
          Guillaume wrote on 16 April 2010:

          I observe conflicts when checking out the
          'private' folder for lmoutr.mex*, plgndr.mex*, ptriproj.*,
          solid_angle.mex*. My understanding is that these files are checked out
          first as normal files and then checked out again as being file externals.
          You see this conflict occurring only when doing a fresh checkout, not a
          subsequent update.
      - +@isprivate: "0"
        commentid: "130"
        comment_count: "1"
        who:
          +content: s.klanke
          +@name: Stefan Klanke
        bug_when: 2010-04-28 16:03:46 +0200
        thetext: |-
          s.klanke: I tried a fresh checkout on both Windows (TortoiseSVN 1.6.7/Subversion 1.6.9) and Linux (svn --version => 1.6.9) and I don't get these conflicts.
          @Guillaume: Which SVN client do you use?
      - +@isprivate: "0"
        commentid: "1183"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-01-26 15:37:20 +0100
        thetext: |-
          I closed all bugs that were resolved prior and including 2011-01-25.

          All resolved bugs should have been discussed by now, therefore we don't want to see them again in the next meeting. Instead, in the next meeting we want to see the recent improvements and fixes.
      - +@isprivate: "0"
        commentid: "1232"
        comment_count: "3"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2011-01-26 15:38:40 +0100
        thetext: |-
          I closed all bugs that were resolved prior and including 2011-01-25.

          All resolved bugs should have been discussed by now, therefore we don't want to see them again in the next meeting. Instead, in the next meeting we want to see the recent improvements and fixes.
